/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import confi.conexion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LAB26
 */
public class GranHotelVillaSur extends javax.swing.JFrame {

    /**
     * Creates new form GranHotelVillaSur
     */
        conexion con=new conexion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int ID;
    public GranHotelVillaSur() {
        initComponents();
        H_listar_JoseZegarra();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        NOMBRES_label_JoseZegarra = new javax.swing.JLabel();
        txt_NOMBRES_JoseZegarra = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txt_CORREO_JoseZegarra = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txt_CELULAR_JoseZegarra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_TIPOHABITACION_JoseZegarra = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        txt_FECHASALIDA_JoseZegarra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txt_NUMEROHABITACIONES_JoseZegarra = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txt_NUMEROPERSONAS_JoseZegarra = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_COSTO_JoseZegarra = new javax.swing.JSpinner();
        jLabel10 = new javax.swing.JLabel();
        txt_METODOPAGO_JoseZegarra = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txt_FECHAENTRADA_JoseZegarra1 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        btnAgregar_JoseZegarra6 = new javax.swing.JButton();
        btnModificar_JoseZegarra = new javax.swing.JButton();
        bntdEliminar_JoseZegarra = new javax.swing.JButton();
        btnLimpiar_JoseZegarra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Lista = new javax.swing.JTable();
        txt_PETICIONES2_JoseZegarra = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setText("GRAN HOTEL VILLA DEL SUR / CRUD ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        NOMBRES_label_JoseZegarra.setText("NOMBRES");

        txt_NOMBRES_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NOMBRES_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel3.setText("CORREO");

        txt_CORREO_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CORREO_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel4.setText("CELULAR");

        txt_CELULAR_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_CELULAR_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel6.setText("TIPO DE HABITACION");

        txt_TIPOHABITACION_JoseZegarra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SIMPLE", "DOBLE", "FAMILIAR", "MATRIMONIAL" }));
        txt_TIPOHABITACION_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_TIPOHABITACION_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel7.setText("FECHA DE SALIDA");

        txt_FECHASALIDA_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FECHASALIDA_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel8.setText("NUMEROHABITACIONES");

        txt_NUMEROHABITACIONES_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NUMEROHABITACIONES_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel9.setText("NUMERO DE PERSONAS");

        txt_NUMEROPERSONAS_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_NUMEROPERSONAS_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel12.setText("PETICIONES");

        jLabel11.setText("COSTO");

        jLabel10.setText("METODO DE PAGO");

        txt_METODOPAGO_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_METODOPAGO_JoseZegarraActionPerformed(evt);
            }
        });

        jLabel14.setText("FECHA ENTRADA");

        txt_FECHAENTRADA_JoseZegarra1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_FECHAENTRADA_JoseZegarra1ActionPerformed(evt);
            }
        });

        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Botones", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(73, 165, 224))); // NOI18N

        btnAgregar_JoseZegarra6.setBackground(new java.awt.Color(0, 204, 0));
        btnAgregar_JoseZegarra6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnAgregar_JoseZegarra6.setText("AGREGAR");
        btnAgregar_JoseZegarra6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregar_JoseZegarra6ActionPerformed(evt);
            }
        });

        btnModificar_JoseZegarra.setBackground(new java.awt.Color(204, 204, 0));
        btnModificar_JoseZegarra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnModificar_JoseZegarra.setText("MODIFICAR");
        btnModificar_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificar_JoseZegarraActionPerformed(evt);
            }
        });

        bntdEliminar_JoseZegarra.setBackground(new java.awt.Color(255, 0, 0));
        bntdEliminar_JoseZegarra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bntdEliminar_JoseZegarra.setText("ELIMINAR");
        bntdEliminar_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntdEliminar_JoseZegarraActionPerformed(evt);
            }
        });

        btnLimpiar_JoseZegarra.setBackground(new java.awt.Color(204, 204, 204));
        btnLimpiar_JoseZegarra.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnLimpiar_JoseZegarra.setText("LIMPIAR");
        btnLimpiar_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiar_JoseZegarraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(btnAgregar_JoseZegarra6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bntdEliminar_JoseZegarra, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLimpiar_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLimpiar_JoseZegarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bntdEliminar_JoseZegarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnModificar_JoseZegarra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAgregar_JoseZegarra6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        Lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRES", "CORREO", "CELULAR", "FECHAENTRADA", "FECHASALIDA", "TIPOHABITACION", "NUMEROHABITACIONES", "NUMEROPERSONAS", "PETICIONES", "METODOPAGO", "COSTO"
            }
        ));
        Lista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Lista);

        txt_PETICIONES2_JoseZegarra.setText("SI");
        txt_PETICIONES2_JoseZegarra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_PETICIONES2_JoseZegarraActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(246, 246, 246)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txt_NUMEROPERSONAS_JoseZegarra)
                                .addComponent(txt_NUMEROHABITACIONES_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txt_PETICIONES2_JoseZegarra))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_FECHAENTRADA_JoseZegarra1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_FECHASALIDA_JoseZegarra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(NOMBRES_label_JoseZegarra)
                        .addComponent(jLabel3)
                        .addComponent(jLabel6))
                    .addGap(64, 64, 64)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_CELULAR_JoseZegarra, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                        .addComponent(txt_NOMBRES_JoseZegarra)
                        .addComponent(txt_CORREO_JoseZegarra)
                        .addComponent(txt_TIPOHABITACION_JoseZegarra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGap(312, 312, 312)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel11)
                        .addComponent(jLabel10))
                    .addGap(72, 72, 72)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txt_METODOPAGO_JoseZegarra, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                        .addComponent(txt_COSTO_JoseZegarra))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(txt_NUMEROHABITACIONES_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_NUMEROPERSONAS_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel4)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txt_PETICIONES2_JoseZegarra)))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txt_FECHASALIDA_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)))
                        .addComponent(txt_FECHAENTRADA_JoseZegarra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(186, 186, 186)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(NOMBRES_label_JoseZegarra)
                                .addComponent(txt_NOMBRES_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(txt_CORREO_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txt_CELULAR_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel11)
                                .addComponent(txt_COSTO_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel10)
                                .addComponent(txt_METODOPAGO_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGap(5, 5, 5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addComponent(txt_TIPOHABITACION_JoseZegarra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(262, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_NOMBRES_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NOMBRES_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NOMBRES_JoseZegarraActionPerformed

    private void txt_CORREO_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CORREO_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CORREO_JoseZegarraActionPerformed

    private void txt_CELULAR_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_CELULAR_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_CELULAR_JoseZegarraActionPerformed

    private void txt_TIPOHABITACION_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_TIPOHABITACION_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_TIPOHABITACION_JoseZegarraActionPerformed

    private void txt_FECHASALIDA_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FECHASALIDA_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FECHASALIDA_JoseZegarraActionPerformed

    private void txt_NUMEROHABITACIONES_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NUMEROHABITACIONES_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NUMEROHABITACIONES_JoseZegarraActionPerformed

    private void txt_NUMEROPERSONAS_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_NUMEROPERSONAS_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_NUMEROPERSONAS_JoseZegarraActionPerformed

    private void txt_METODOPAGO_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_METODOPAGO_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_METODOPAGO_JoseZegarraActionPerformed

    private void txt_FECHAENTRADA_JoseZegarra1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_FECHAENTRADA_JoseZegarra1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_FECHAENTRADA_JoseZegarra1ActionPerformed

    
    
    
    private void btnAgregar_JoseZegarra6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregar_JoseZegarra6ActionPerformed
        H_agregar_JoseZegarra();
        H_listar_JoseZegarra();
        H_limpiar_JoseZegarra();
    }//GEN-LAST:event_btnAgregar_JoseZegarra6ActionPerformed

    private void bntdEliminar_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntdEliminar_JoseZegarraActionPerformed
        H_eliminar_JoseZegarra();
        H_listar_JoseZegarra();
        H_limpiar_JoseZegarra();
    }//GEN-LAST:event_bntdEliminar_JoseZegarraActionPerformed

    private void btnModificar_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificar_JoseZegarraActionPerformed
        H_modificar_JoseZegarra();
        H_listar_JoseZegarra();
        H_limpiar_JoseZegarra();
    }//GEN-LAST:event_btnModificar_JoseZegarraActionPerformed

    private void btnLimpiar_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiar_JoseZegarraActionPerformed
        H_limpiar_JoseZegarra();
    }//GEN-LAST:event_btnLimpiar_JoseZegarraActionPerformed

    private void ListaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListaMouseClicked
        int Fila=Lista.getSelectedRow();
        if(Fila==-1){
            JOptionPane.showMessageDialog(null, "elija una fila");
        } else {
            ID=Integer.parseInt((String)Lista.getValueAt(Fila, 0).toString());ID=Integer.parseInt((String)Lista.getValueAt(Fila, 0).toString());
            String NOMBRES=(String)Lista.getValueAt(Fila, 1);
            String CORREO=(String)Lista.getValueAt(Fila, 2);
            String CELULAR=(String)Lista.getValueAt(Fila, 3);
            String FECHAENTRADA=(String)Lista.getValueAt(Fila, 4);
            String FECHASALIDA=(String)Lista.getValueAt(Fila, 5);
            String TIPOHABITACION=(String)Lista.getValueAt(Fila, 6);
            String NUMEROHABITACIONES=(String)Lista.getValueAt(Fila, 7);
            String NUMEROPERSONAS=(String)Lista.getValueAt(Fila, 8);
            boolean PETICIONES = Boolean.parseBoolean((String)Lista.getValueAt(Fila, 9));
            String METODOPAGO=(String)Lista.getValueAt(Fila, 10);
            String COSTO=(String)Lista.getValueAt(Fila, 11);
            txt_NOMBRES_JoseZegarra.setText(NOMBRES);
            txt_CORREO_JoseZegarra.setText(CORREO);
            txt_CELULAR_JoseZegarra.setText(CELULAR);
            txt_FECHAENTRADA_JoseZegarra1.setText(FECHAENTRADA);
            txt_FECHASALIDA_JoseZegarra.setText(FECHASALIDA);
            txt_TIPOHABITACION_JoseZegarra.setSelectedItem(TIPOHABITACION);
            txt_NUMEROHABITACIONES_JoseZegarra.setText(NUMEROHABITACIONES);
            txt_NUMEROPERSONAS_JoseZegarra.setText(NUMEROPERSONAS);
            txt_PETICIONES2_JoseZegarra.setSelected(PETICIONES);
            txt_METODOPAGO_JoseZegarra.setText(METODOPAGO);
            txt_COSTO_JoseZegarra.setValue(Integer.parseInt(COSTO));

        }
    }//GEN-LAST:event_ListaMouseClicked

    private void txt_PETICIONES2_JoseZegarraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_PETICIONES2_JoseZegarraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_PETICIONES2_JoseZegarraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GranHotelVillaSur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GranHotelVillaSur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GranHotelVillaSur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GranHotelVillaSur.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GranHotelVillaSur().setVisible(true);
            }
        });
    }

    
    void H_listar_JoseZegarra() {
    String sql = "SELECT * FROM HOTELVILLA";
    try {
        cn = con.getConnection();
        st = cn.createStatement();
        rs = st.executeQuery(sql);
        
        modelo = (DefaultTableModel) Lista.getModel();
        modelo.setRowCount(0);
        
        while (rs.next()) {
            Object[] fila = new Object[13];
            fila[0] = rs.getInt("ID");
            fila[1] = rs.getString("NOMBRES");
            fila[2] = rs.getString("CORREO");
            fila[3] = rs.getString("CELULAR");
            fila[4] = rs.getString("FECHAENTRADA");
            fila[5] = rs.getString("FECHASALIDA");
            fila[6] = rs.getString("TIPOHABITACION");
            fila[7] = rs.getString("NUMEROHABITACIONES");
            fila[8] = rs.getString("NUMEROPERSONAS");
            fila[9] = rs.getString("PETICIONES");
            fila[10] = rs.getString("METODOPAGO");
            fila[11] = rs.getString("COSTO");
            
            modelo.addRow(fila);
        }
        
        Lista.setModel(modelo);
        
    } catch (Exception e) {
        e.printStackTrace();
    }
}


        void H_limpiartabla_JoseZegarra(){
        for(int i=0;i<=Lista.getRowCount();i++){
            modelo.removeRow(i);
            i=i-1;
        }
    }
     void H_agregar_JoseZegarra(){
        String NOMBRES=txt_NOMBRES_JoseZegarra.getText();
        String CORREO=txt_CORREO_JoseZegarra.getText();
        String CELULAR=txt_CELULAR_JoseZegarra.getText();
        String FECHAENTRADA=txt_FECHAENTRADA_JoseZegarra1.getText();
        String FECHASALIDA=txt_FECHASALIDA_JoseZegarra.getText();
        String TIPOHABITACION = (String) txt_TIPOHABITACION_JoseZegarra.getSelectedItem();
        String NUMEROHABITACIONES=txt_NUMEROHABITACIONES_JoseZegarra.getText();
        String NUMEROPERSONAS=txt_NUMEROPERSONAS_JoseZegarra.getText();
        boolean PETICIONES = txt_PETICIONES2_JoseZegarra.isSelected();
        String METODOPAGO =txt_METODOPAGO_JoseZegarra.getText();
        String COSTO=txt_COSTO_JoseZegarra.getValue().toString();
        if(NOMBRES.equals("")||CORREO.equals("")||CELULAR.equals("")||FECHAENTRADA.equals("")||FECHASALIDA.equals("") ||TIPOHABITACION.equals("")||NUMEROHABITACIONES.equals("")
                ||NUMEROPERSONAS.equals("")||METODOPAGO.equals("") ||COSTO.equals("")){
            
            JOptionPane.showMessageDialog(null, "debe de agregar datos a los campos");
        } else{
        String sql = "INSERT INTO HOTELVILLA (NOMBRES, CORREO, CELULAR, FECHAENTRADA, FECHASALIDA, TIPOHABITACION, NUMEROHABITACIONES, NUMEROPERSONAS, PETICIONES, METODOPAGO, COSTO) VALUES "
                     + "('" + NOMBRES + "','" + CORREO + "','" + CELULAR + "',STR_TO_DATE('" + FECHAENTRADA + "', '%d-%m-%Y'),STR_TO_DATE('" + FECHASALIDA + "', '%d-%m-%Y'),'" + TIPOHABITACION + "','" + NUMEROHABITACIONES + "','" + NUMEROPERSONAS + "','" + PETICIONES + "','" + METODOPAGO + "','" + COSTO + "')";
           try {
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "RESERVA AGREGADA CON EXITO");
                H_limpiartabla_JoseZegarra();
            } catch (Exception e) {
            }
        }
    }
    
void H_modificar_JoseZegarra(){
    String NOMBRES = txt_NOMBRES_JoseZegarra.getText();
    String CORREO = txt_CORREO_JoseZegarra.getText();
    String CELULAR = txt_CELULAR_JoseZegarra.getText();
    String FECHAENTRADA = txt_FECHAENTRADA_JoseZegarra1.getText();
    String FECHASALIDA = txt_FECHASALIDA_JoseZegarra.getText();
    String TIPOHABITACION = (String) txt_TIPOHABITACION_JoseZegarra.getSelectedItem();
    String NUMEROHABITACIONES = txt_NUMEROHABITACIONES_JoseZegarra.getText();
    String NUMEROPERSONAS = txt_NUMEROPERSONAS_JoseZegarra.getText();
    boolean PETICIONES = txt_PETICIONES2_JoseZegarra.isSelected();
    String METODOPAGO = txt_METODOPAGO_JoseZegarra.getText();
    String COSTO = txt_COSTO_JoseZegarra.getValue().toString();
    
    if (NOMBRES.equals("") || CORREO.equals("") || CELULAR.equals("") || FECHAENTRADA.equals("") || FECHASALIDA.equals("") || TIPOHABITACION.equals("") || NUMEROHABITACIONES.equals("")
            || NUMEROPERSONAS.equals("")|| METODOPAGO.equals("") || COSTO.equals("")) {
        JOptionPane.showMessageDialog(null, "Elija una fila para modificar");
    } else {
        String sql = "UPDATE HOTELVILLA SET NOMBRES='" + NOMBRES + "', CORREO='" + CORREO + "', CELULAR='" + CELULAR + "', FECHAENTRADA='" + FECHAENTRADA + "', FECHASALIDA='" + FECHASALIDA + "', TIPOHABITACION='" + TIPOHABITACION + "', NUMEROHABITACIONES='" + NUMEROHABITACIONES + "', NUMEROPERSONAS='" + NUMEROPERSONAS + "', PETICIONES=" + PETICIONES + ", METODOPAGO='" + METODOPAGO + "', COSTO='" + COSTO + "' WHERE ID=" + ID;
    try {
            cn = con.getConnection();
            st = cn.createStatement();
            st.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "DATOS DE RESERVA MODIFICADA CON EXITO");
            H_limpiartabla_JoseZegarra();
            H_listar_JoseZegarra();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
}

      void H_eliminar_JoseZegarra(){
        int FilaSeleccionada=Lista.getSelectedRow();
        if(FilaSeleccionada==-1){
            JOptionPane.showMessageDialog(null, "elija una fila que quiera eliminar");
        } else {
            String sql="DELETE FROM HOTELVILLA WHERE id="+ID;
            try {
                cn=con.getConnection();
                st=cn.createStatement();
                st.executeUpdate(sql);
                JOptionPane.showMessageDialog(null, "RESERVA ELIMINADA CON EXITO");
                H_limpiartabla_JoseZegarra();
            } catch (Exception e) {
            }
        }
    }


    void H_limpiar_JoseZegarra(){
        txt_NOMBRES_JoseZegarra.setText("");
        txt_CORREO_JoseZegarra.setText("");
        txt_CELULAR_JoseZegarra.setText("");
        txt_FECHAENTRADA_JoseZegarra1.setText("");
        txt_TIPOHABITACION_JoseZegarra.setSelectedItem("");
        txt_FECHASALIDA_JoseZegarra.setText("");
        txt_NUMEROHABITACIONES_JoseZegarra.setText("");
        txt_NUMEROPERSONAS_JoseZegarra.setText("");
        txt_PETICIONES2_JoseZegarra.setSelected(false);
        txt_COSTO_JoseZegarra.setValue(0);
        txt_METODOPAGO_JoseZegarra.setText("");
        txt_CORREO_JoseZegarra.requestFocus();
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Lista;
    private javax.swing.JLabel NOMBRES_label_JoseZegarra;
    private javax.swing.JButton bntdEliminar_JoseZegarra;
    private javax.swing.JButton btnAgregar_JoseZegarra6;
    private javax.swing.JButton btnLimpiar_JoseZegarra;
    private javax.swing.JButton btnModificar_JoseZegarra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt_CELULAR_JoseZegarra;
    private javax.swing.JTextField txt_CORREO_JoseZegarra;
    private javax.swing.JSpinner txt_COSTO_JoseZegarra;
    private javax.swing.JTextField txt_FECHAENTRADA_JoseZegarra1;
    private javax.swing.JTextField txt_FECHASALIDA_JoseZegarra;
    private javax.swing.JTextField txt_METODOPAGO_JoseZegarra;
    private javax.swing.JTextField txt_NOMBRES_JoseZegarra;
    private javax.swing.JTextField txt_NUMEROHABITACIONES_JoseZegarra;
    private javax.swing.JTextField txt_NUMEROPERSONAS_JoseZegarra;
    private javax.swing.JRadioButton txt_PETICIONES2_JoseZegarra;
    private javax.swing.JComboBox<String> txt_TIPOHABITACION_JoseZegarra;
    // End of variables declaration//GEN-END:variables
}
